# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: lind
spec:
  type: team
  children: [lind-user1]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: lind-user1
spec:
  memberOf: [lind]
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backend-system
spec:
  owner: lind
---
apiVersion: backstage.io/v1alpha1
kind: Component # 类型，api,component,group,location,system,user
metadata:
  name: lind-admin  # 组件的唯一名称
  description: lind小后台-微小的后台  # 组件描述
  annotations:
    github.com/project-slug: https://github.com/bfyxzls/lind-admin  # GitHub仓库地址
    backstage.io/techdocs-ref: dir:.  # 自动在当前目录进行扫描
    backstage.io/multi-format-docs: '["2025apisix接入文档.xlsx", "Elasticsearch for Hadoop.epub","TOTP.pdf","刷新token会议后的开发计划.docx"]'
  labels:
    business-unit: backend  # 业务单元标签
  tags:
    - java
    - spring-boot
    - microservice
spec:
  type: service  # 组件类型：service、website、library等
  lifecycle: production  # 生命周期阶段：experimental、production、deprecated
  owner: lind  # 负责团队
  system: backend-system  # 所属系统（可选）
  domain: lind-domain  # 所属领域（可选）
  providesApis:
    - lind-admin-grpc-api  # 提供的API
  dependsOn:
    - component:keycloak-report
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: lind-admin-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: lind
  system: backend-system
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
